version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 7000:7000
    environment:
      NODE_ENV: development
      PORT: 7000
      TZ: America/Sao_Paulo
      DATABASE_URI: mongodb://root:root@db/dados
    volumes:
      - .:/app
  db:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  database:
